### ISSUE TITLE
Support Webpack 4.0

### ISSUE THREAD

**Issue by MaxGraey** [alexcrichton/wasm-bindgen#39]
Since webpack 4.0 beta released we can implicitly import wasm files.

**Comment by alexcrichton** [comment]
Oh nice! I've love to land support for this :)

I gave this a spin locally and unfortunately it looks like this won't work out of the box yet as we're getting the error "Sync WebAssembly compilation is not yet implemented". The wasm-bindgen tool generates a JS file that looks like:

```js
// foo.js
import * as wasm from "./foo_wasm";

// ...
```

and then it also emits a `foo_wasm.wasm` file next to it. It seems, though, that Webpack hasn't implemented this part of the functionality of importing wasm files yet? It looks like `import("./foo_wasm")` does indeed work, but I'm unfortunately a bit of a newbie when it comes to asynchronous imports and such.

I'm not sure how to resolve this, but I'd imagine it's for sure fixable! Is there a way to require that the JS shim is itself asynchronously imported as well? We could probably hook in the wasm import promise into that in that case, but otherwise I'm not sure what the best way is to deal with the promise returned from the import of the wasm...

**Comment by MaxGraey** [comment]
in webpack 4.0 this shipping as experimental feature and turn off by default (on may turn very limit functionality).

Are you try this?:
```javascript
rules: [{
  test: /\.wasm$/,
  type: "webassembly/experimental"
}]
```

**Comment by alexcrichton** [comment]
@MaxGraey I think I tried that out yeah (although I'm also a newbie at webpack) but it didn't look to change the error message

**Comment by MaxGraey** [comment]
This is [simple webpack config](https://github.com/webpack/webpack/blob/master/examples/wasm-simple/webpack.config.js) from [this](https://github.com/webpack/webpack/tree/master/examples/wasm-simple) official example. Still not helped?

PS I'm not sure
```js
import * as wasm from "./foo_wasm";
```
Support in beta. Try to rewrite this to:
```js
import * as wasm from "./foo_wasm.wasm";
```

**Comment by alexcrichton** [comment]
@MaxGraey nah unfortunately the extension doesn't help, the problem here is that webpack I believe [does not implement this functionality  yet](https://github.com/webpack/webpack/blob/6a5d081f294a225d9f02b56c55fdcd61b7b4db20/lib/wasm/WasmModuleTemplatePlugin.js#L18). This library currently assumes that `import` can be compiled to work synchronously when importing from a wasm module, but this isn't imported in webpack yet.

Switching to using `import('./foo_wasm')` does indeed work with webpack (yay!) but it unfortunately runs into https://github.com/webpack/webpack/issues/6475 very quickly in Chrome.

I've opened up https://github.com/webpack/webpack/issues/6615 for synchronously importing wasm modules.

**Comment by sendilkumarn** [comment]
> a bit of a newbie when it comes to asynchronous imports and such.

what will be the problem here, It would be great to add in a loader in webpack to do this. taking inspiration from `walt-loader`


> but I'd imagine it's for sure fixable! Is there a way to require that the JS shim is itself asynchronously imported as well?


What do you mean here, import it in the JS file and then use `async` import that javascript file -> that is doable. IIUC ( the sample test does it)

**Comment by alexcrichton** [comment]
@sendilkumarn yeah ideally what I'm thinking of is something like:

```js
// at the top level
let wasm = await import('./foo_wasm');
```

sort of making it an "async module". This doesn't work today, however, and I'm not actually sure how it could work...

**Comment by sendilkumarn** [comment]
w.r.t `wasm-bindgen` ?

**Comment by alexcrichton** [comment]
@sendilkumarn yeah I'm currently wonder what to generate in the `wasm-bindgen` tool and how it is consumed by other JS files.

**Comment by sendilkumarn** [comment]
but just an update (based on the discussion we had), you cannot use the sync import in the main chunk. But you can use it in other places. By this, if you have another JS file where you can use it via normal import syntax (`sync` ones) on the other hand, in the main chunk file you should use `async` import.

**Comment by alexcrichton** [comment]
Aha awesome! To confirm @sendilkumarn (sorry I'm very much a JS newb) you mean this, right?

```js
// index.js
let foo = import('./foo.js');

// foo.js
import { foo } from './foo.wasm';

export const bar = foo;
```

Because that does indeed work with webpack today! (yay!)

To confirm though, this is expected to not work, right?

```js
// index.js
import { foo } from './foo.js';

// foo.js
import { foo } from './foo.wasm';

export const bar = foo;
```

**Comment by MaxGraey** [comment]
I think sothing like this:
**impors.js**:
```js
import { foo } from './foo.wasm';
import { boo } from './boo.wasm';

export { foo, boo };
```

**index.js**:
```js
// async wrapper
void async function () {
   const { foo, boo } = await import('./impors.js');
   ...
} ();
```

**Comment by sendilkumarn** [comment]
@alexcrichton 

```js
// foo.js
import { foo } from './foo.wasm';
// call foo
foo()
```
this will work, except that it should not be your chunk's main file. in other words (`index.js`)

In `index.js` it should be `async`.

https://github.com/webpack/webpack/blob/master/test/cases/wasm/simple/module.js

P.S. this is kinda super weird for me but this is how it works.

**Comment by alexcrichton** [comment]
Ok! Turns out no actual code changes were needed for this issue, but I've rewritten the intro example in the README to use Webpack as a bundler, so I'm going to close this.

**Comment by alexcrichton** [comment]
Thanks so much for the tip @sendilkumarn!

**Comment by benma** [comment]
> Ok! Turns out no actual code changes were needed for this issue, but I've rewritten the intro example in the README to use Webpack as a bundler, so I'm going to close this.

@alexcrichton could you please share a link to this? We are having trouble getting this to work on webpack4.
