### ISSUE TITLE
question: why `cargo install` and add as a dep in Cargo.toml

### ISSUE THREAD

**Issue by ashleygwilliams** [alexcrichton/wasm-bindgen#44]
i may just not be fully understanding but i am curious as to why i need to add wasm-bindgen as a dep of my project as well as run `cargo install` for it.

**Comment by alexcrichton** [comment]
A good question! Currently the way wasm-bindgen is architected is that it runs in two phases, corresponding to the dependency and the binary tool. The first phase, the dependency, is providing things like runtime support in the Rust program (`JsValue` and such) as well as the macro to generate shims for Rust code (`#[wasm_bindgen]`). This is what actually modifies the wasm binary emitted and makes it "ABI compatible" with talking to JS. For example you write `pub fn foo(a: &str)` and what's actually exported is something like `pub fn foo_shim(a: *const u8, b: usize)` so it can be called from JS.

The binary tool is then the second phase which runs after the wasm binary is fully generated. This tool extracts the wasm-bindgen descriptor sections and generates JS files (and tweaks the wasm a bit). Currently this is needed as a separate step for a few reasons:

* The rust compiler itself doesn't have a way to generate a JS file anywhere, so it's not clear where as part of the build process this would otherwise happen.
* Ideally the wasm-bindgen tool is Rust-independent in the sense that it doesn't actually require the wasm file originated from rustc or even contains Rust code, but rather it's a postprocessor of a wasm file that could also be generated from C/C++

Does that makes sense?

**Comment by alexcrichton** [comment]
Closing, but if anything's not clear I can of course elaborate!

**Comment by ashleygwilliams** [comment]
(sorry for not replying sooner, this answer was perfect thank u)
