### ISSUE TITLE
Just get typings for exports

### ISSUE THREAD

**Issue by qm3ster** [alexcrichton/wasm-bindgen#49]
In order to just get .d.ts types for a rust file compiled to wasm, should I use this project or is there something more suitable?
Also, in my case, all `<projectname>.js` does is reexport functions already exported in `<projectname>_wasm.js`, and `<projectname>.d.ts` is provided for that, meaining it doesn't export for example the `memory` or even the `booted` promise (how can I know when I can start using the module, do I need to import both, one for the promise the other for booted actions?)

I am looking for something that, based on a rust file, produces the definition of a custom `ResultObject` where `instance.exports` is statically typed.
Maybe the return of `WebAssembly.Module.exports()`, but that's less significant.

**Comment by alexcrichton** [comment]
Ah yes indeed! So interacting with the wasm file in a more raw fashion isn't great supported today. You can use `wasm2es6js` to extract a `*.d.ts` file describing the wasm module, but that's a bit of a hack because that's not ideally what the tool is intended to do.

The `booted` promise is actually specific to `wasm2es6js` as the native wasm module doesn't have that. To import the memory though you should be able to do `import { memory } from `./foo_wasm';` and I think that should work out alright.

As to when you can start using the wasm module it sort of depends on the bundler you're using and how it's hooked up into the rest of the application, the thinking behind `#[wasm_bindgen]` is that instantiation is left to a different stage.

Does that help though? Or maybe some pieces still need some clarification?

**Comment by qm3ster** [comment]
Crystal clear. And I'm sure these layers would be useful to me if I was using the advanced features like passing javascript objects.
But I was just looking for something that would augment the normal wasm32-unknown-unknown output with a `.d.ts` like this:
```rust
#[no_mangle]
pub fn make_point(x: f32, y: f32) -> *mut ::std::os::raw::c_void {
  //...
  sliceptr as *mut ::std::os::raw::c_void
}
```
```ts
interface MyResult extends WebAssembly.ResultObject {
  instance: {
    readonly exports: {
      memory: WebAssembly.Memory;
      //note that the arguments are named, bindgen currently calls them `arg0` and `arg1`
      make_point(x: number, y: number): number;
    };
  };
}
export default function(): Promise<MyResult>;
```
Not sure where to best get started to make that myself or if that's possible for me at all.
