### ISSUE TITLE
question: why name the wasm file `<inflected_crate_name>_wasm.wasm`

### ISSUE THREAD

**Issue by ashleygwilliams** [alexcrichton/wasm-bindgen#52]
the wasm part seems redundant. was just curious why it's named this way ;)

**Comment by sendilkumarn** [comment]
to differentiate the wasm from rustc and wasm from bindgen. It should be replaced with something like `bg` or `bind` 📦

**Comment by alexcrichton** [comment]
Ah yeah it basically needed to be anything other than `$crate.wasm` because `$crate.js` needed to exist and would cause conflicts (I think?) with `import { x } from './$crate';`

I just randomly picked `_wasm` off the top of my head but something like `_bg_wasm` + `_bg_shims` would probably be a better idea!

**Comment by sendilkumarn** [comment]
Okay this seems like a really `good-first-issue` I will try to take a crack on this one.

**Comment by alexcrichton** [comment]
Certainly! @sendilkumarn if you need any help just lemme know!

**Comment by alexcrichton** [comment]
Sure!
