### ISSUE TITLE
Can I import multiple version of a js function based on its arity? If yes, how?

### ISSUE THREAD

**Issue by akritrime** [alexcrichton/wasm-bindgen#72]
For example, I have this js module `test.js`.
```js
export function test(a) {
    return a || 1
}
```
Now in js, I can call this function with or without an argument. Can I mimic the same thing on rust side with something like this?

```rust
#[wasm_bindgen(module = "./test")]
extern {
    fn test(i: i32) -> i32;
    #[wasm_bindgen(...some attr indicating its the same function on JS side)]
    fn test_without_arg() -> i32;
}
```

**Comment by alexcrichton** [comment]
Ah yeah this isn't currently implemented but I don't think it'd be too hard! I think we can crib off the existing `#[link_name]` in Rust and support this as:

```rust
#[wasm_bindgen(module = "./test")]
extern {
    fn test(i: i32) -> i32;
    #[link_name = "test"]
    fn test_without_arg() -> i32;
}
```

This'll require some cleanup on the code generation though because I think the symbols would conflict otherwise (we still need to generate two shims here)

**Comment by alexcrichton** [comment]
Ended up implementing it a bit differently but let me know if anything looks off!

**Comment by akritrime** [comment]
Nope, looks good.
